name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Maintenance'
    label: 'chore'
template: |
  ## Changes
  $CHANGES
